# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 🏠 Home
    url: /
    weight: 10
  - name: 🔎 Research Topics
    url: /topics/
    weight: 11
  - name: 👥 Team
    url: team/
    weight: 12
  - name: 📄 Publications
    url: /publications/
    weight: 13
  - name: 👥 News
    url: /news/
    weight: 14
  - name: 📂 Projects & Collaborations
    url: /projects/
    weight: 15